name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install -r requirements-dev.txt
      - name: Test
        run: tox -e py
      - name: Test coverage
        run: tox -e coverage
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install tox
        run: pip install -r requirements-dev.txt
      - name: Test
        run: tox -e coverage
